### PR TITLE
use ship raster tif file directly instead of converted nc file

### PR DESCRIPTION
**Pull request by FabianHofmann**
closes #474 

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

### CODE REVIEW

**Comment by fneum** [comment]
The build shapes script is no longer necessary, is it?

Has this been tested for functionality and performance degression already?

**Comment by fneum** [comment]
Hmm, I think we shouldn't skip cutting to the geographical scope of the model. The extracted `.tif` is 10 GB large. Also RAM requirements are higher for me.

**Comment by FabianHofmann** [comment]
Did you see large differences? Performance wise it was just a couple of seconds for me and memory use was also not high. Alternatively we could clip the tif file before writing to file.

**Comment by fneum** [comment]
I’d definitely clip it. I am more worried about the 10 GB of disk space than little higher memory usage.

**Pull request closed without merging**
