### PR TITLE
add_electricity.py & config.yaml: Add a simple load scaler

### PR DESCRIPTION
**Pull request by Heronimonimo**

### CODE REVIEW

**Comment by coroa** [comment]
Is the term `load scaler` commonly used? I would have called it plainly `factor`.

**Comment by coroa** [comment]
Can you please, in the future, follow my convention to prefix commit messages with the affected rule, if it's just one or two of them! (refer to https://github.com/PyPSA/pypsa-eur/commits/master)

**Comment by Heronimonimo** [comment]
The idea was to make a category for the load in the config with a sub for scaling it. Scaler seems to me the appropriate term as it scales the load.

**Comment by coroa** [comment]
Is `load: scaling_factor` as a name a good compromise :) ?

**Comment by Heronimonimo** [comment]
Yeah, sure. Updated the commit to with the scaling_factor name.

**Pull request merged**
