### PR TITLE
Update to OSM-prebuilt v0.6

### PR DESCRIPTION
**Pull request by bobbyxng**
Closes # (if applicable).

## Changes proposed in this Pull Request
- Added interactive map to the Zenodo databundle: https://zenodo.org/records/14144752
- Can be directly accessed through: https://pypsa-eur.readthedocs.io/en/latest/data-base-network.html Thanks @lkstrp 
- Prebuilt network includes all technical parameters (impedance, nominal current, reactance, susceptance, etc.) for potential use outside PyPSA/PyPSA-Eur
- Scripts `build_osm_network` and `prepare_osm_network_release` reflect this change and include the construction of the interactive map. Base network and subsequent steps are not impacted by this. 
- I have tested the model at hourly resolution for the target year, model converges, results are similar to the gridkit-based network.

## Checklist

- [X] I tested my contribution locally and it works as intended.
- [X] Code and workflow changes are sufficiently documented.
- [X] Changed dependencies are added to `envs/environment.yaml`.
- [X] Changes in configuration options are added in `config/config.default.yaml`.
- [X] Changes in configuration options are documented in `doc/configtables/*.csv`.
- [X] Sources of newly added data are documented in `doc/data_sources.rst`.
- [X] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
@bobbyxng I have problems with the retrieval of map.html. they are not included in the zenodo repo. Is that perhaps something for future zenodo versions?

**Comment by bobbyxng** [comment]
> @bobbyxng I have problems with the retrieval of map.html. they are not included in the zenodo repo. Is that perhaps something for future zenodo versions?

Hi @FabianHofmann ! I just did a test using the latest pypsa-eur master branch, for me `map.html`is downloaded just like all other files. Note the file only exists from version 0.6 onwards. Download takes a bit longer (in my case around 30 seconds), as it's quite large at >40 MB

**Comment by FabianHofmann** [comment]
Gotcha! thanks, I still had the old version!

**Comment by FabianHofmann** [comment]
on the other hand this means that the osm version setting is obsolete. At least setting version <0.6, which the current code suggests to be working, breaks. I would suggest to either only support version tags >= 0.6 or make the code flexible to support also older versions

**Pull request merged**
