### PR TITLE
Nomopyomo

### LINKED ISSUE #113: incorporate network.ilopf() from pypsa v0.16.0 in solve_network
related #19

### LINKED ISSUE #114: incorporate network.lopf(pyomo=False) from pypsa v0.16.0 in solve_network
... for orientation cf. nworbmot/pypsa-eur-sec

### PR DESCRIPTION
**Pull request by FabianHofmann**
Closes #114 
Closes #113 

## Changes proposed in this Pull Request

Shift optimisation to not rely on pyomo. One could also have both pyomo and nomopyomo available, even though I would make the case for only having one optimisation framework, as the code is getting bloated otherwise (and testing as well). 

Overview: 
* BAU, SAFE, CCL constraints are now defined in separate functions 
* constraints for store links are added, equivalent to the one in pypsa-eur-sec 
* all additional constraints are passed to the `lopf` via `extra_functionality()` 
* the argument `config`  in `solve_network` now expects the whole snakemake.config
* the snakemake variable is pulled out of functions in `solve_network.py` for easy reuse in `solve_operations_network.py`
* trace_solve_network.py was removed in favour of upcoming implementation in pypsa (https://github.com/PyPSA/PyPSA/issues/129)
* the envrironment.yaml was updated as the CI for windows machines raised an error caused be strict reliance on conda-forge channel (`defaults` was added)
* `skip_iterating` and `track_iterations` can now be set in the config.yaml. **pypsa version has to be up to date with current master**

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `environment.yaml` and `environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
Open questions: Is the trace_solve_network script necessary? If not, what would be less work, we could delete it.

**Comment by fneum** [comment]
I think it is a useful diagnostic feature and not too much work to maintain, don't you think? I would however not oppose merging the function for saving optimal capacities for each iteration into `solve_network` directly and making it an option in the `config.yaml`.

CI has failed on Windows with 

```bash
ImportError: DLL load failed: The specified module could not be found.
```

See https://travis-ci.org/PyPSA/pypsa-eur/builds/642603801?utm_source=github_status&utm_medium=notification

**Comment by FabianHofmann** [comment]
> CI has failed on Windows with
> 
> ```shell
> ImportError: DLL load failed: The specified module could not be found.
> ```
> 
> See https://travis-ci.org/PyPSA/pypsa-eur/builds/642603801?utm_source=github_status&utm_medium=notification

yes, it's a weird error, seems to be related with https://github.com/conda-forge/fiona-feedstock/issues/139

**Comment by FabianHofmann** [comment]
This worked now, the channel priority had to be changed...

**Comment by fneum** [comment]
Interesting, thanks for tracing the error down! It might be a few days until I review this, hope this is alright.

**Comment by coroa** [comment]
How does this interact with an integration of the planned `ilopf` pypsa functions?

Last time I checked they were formulated using pyomo, is this PR making a future integration more difficult? Do you need a more modular approach?

**Comment by FabianHofmann** [comment]
Hey @coroa,
 
> How does this interact with an integration of the planned `ilopf` pypsa functions?

The function `ilopf` is already implemented in the [linopf module](https://github.com/PyPSA/PyPSA/blob/6179a7446b383e102ed97f731d3983b266b4beb3/pypsa/linopf.py#L926). It mirrors the code of the current pypsa-eur implementation. 

> Last time I checked they were formulated using pyomo, is this PR making a future integration more difficult? Do you need a more modular approach?

The function works well, I think further breaking it down is not really necessary. 

> Also: I vote for keeping `trace_solve_network`

Alright, my plan was to implement the tracing in `ilopf` function itself, see https://github.com/PyPSA/PyPSA/issues/129 . Through a kwarg (perhaps `trace_impedances`), one can activate the tracking, which is written down in the dataframes of n.passive_branch_components .  
As @fneum proposed, a flag in the config file then enables the tracing. Are you fine with this?

**Comment by FabianHofmann** [comment]
The new feature `track_iterations` can now be set in the config.yaml. However, the pypsa version has to be up to date with the current master branch for this. Two options 
1. Push tom to make a minor release
2. Temporarily install pypsa via pip and the git repo in the environment.yaml

**Comment by coroa** [comment]
Re `ilopf`: The only draw-back is that earlier it was possible to depend on those separate files to make a plot of how the line capacities change, but I suppose, it would be easy to bring something similar back. I am fine with that change.

But I made a mix-up, I meant the code prepared in: https://github.com/PyPSA/PyPSA/pull/127. Would we ever want to run these on pypsa-eur code. Would we have to bring back the pyomo support for this? On the other hand there is always the git history, so nothing is lost anyway. Fine from me.

**Comment by FabianHofmann** [comment]
> Re `ilopf`: The only draw-back is that earlier it was possible to depend on those separate files to make a plot of how the line capacities change, but I suppose, it would be easy to bring something similar back. I am fine with that change.

I see, yes there should be a way to integrate that. 
> 
> But I made a mix-up, I meant the code prepared in: [PyPSA/PyPSA#127](https://github.com/PyPSA/PyPSA/pull/127). Would we ever want to run these on pypsa-eur code. Would we have to bring back the pyomo support for this? On the other hand there is always the git history, so nothing is lost anyway. Fine from me.

I oversaw this PR and have a look into it. @fneum would this then undermine the aim of your PR? Do you see a possibility to integrate it into the new lopf?

**Comment by FabianHofmann** [comment]
Okay, CI passed, this is finally ready for review :)

**Comment by fneum** [comment]
I don't really have ambitions to include https://github.com/PyPSA/PyPSA/pull/127 into PyPSA-Eur immediately. Due to its MILP nature, the size of problems that can be solved is quite limited anyway. Incorporating integer transmission expansion (that is currently implemented with pyomo) wouldn't be a problem when neglecting the additional constraints (e.g. lv, lc, BAU, SAFE...). The function `network.teplopf` would not rely on `network.ilopf`, since it doesn't have to be iterated.

I agree with dropping pyomo in PyPSA-Eur to simplify our lives (while we can). We can always recover it if requests pile up. 

@FabianHofmann I hope you don't mind me pushing on the branch directly. I have deleted the remaining references to `trace_solve_network` and extended the release notes. Also, I thought the abbreviation `sn` for **sn**akemake (e.g. in `n.sn_config`) is becoming too ambiguous. In PyPSA it's already used as abbreviation for **s**ub**n**etworks and **sn**apshots.

**Comment by FabianHofmann** [comment]
> @FabianHofmann I hope you don't mind me pushing on the branch directly. I have deleted the remaining references to `trace_solve_network` and extended the release notes. Also, I thought the abbreviation `sn` for **sn**akemake (e.g. in `n.sn_config`) is becoming too ambiguous. In PyPSA it's already used as abbreviation for **s**ub**n**etworks and **sn**apshots.

Totally agree!

**Pull request merged**
