### PR TITLE
importing rioxarray instead of xarray to open rasterio file

### LINKED ISSUE #644: Restore compatibility with newest xarray
https://docs.xarray.dev/en/stable/whats-new.html#v2023-04-0-april-14-2023

xr.open_rasterio was removed.

## Checklist

- [ ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
<paste here>
```

### PR DESCRIPTION
**Pull request by virio-andreyana**
closes #644
closes #476 

Importing rioxarray instead of xarray to open rasterio file. This is to fix the warning in rule build_ship_raster: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html 

changes had been made in the environment and environment.fixed to add rioxarray

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

### CODE REVIEW

**Review by fneum — COMMENTED** [review]
I remember @p-glaum tested this and had some problems as well.

**Comment by p-glaum** [comment]
> I remember @p-glaum tested this and had some problems as well.

yes, I wanted to use rioxarray as well because I already got the deprecation warning at the time I wrote the shipping raster script. But somehow with rioxarray I could not open the raster data and I think it always crashed. So I switched back to xarray. But if it works now with rioxarray I would also change it as you did @virio-andreyana

**Comment by FabianHofmann** [comment]
@p-glaum do you remember the reason why we you did not choose to convert the tif to a netcdf file in the first place?

**Comment by p-glaum** [comment]
No sorry. I remember I took that detour because the direct way was not working due to some error.

**Comment by FabianHofmann** [comment]
@fneum I can fix the pre-commit CI in separate PR

**Comment by fneum** [comment]
Looks good!

**Pull request merged**
