### PR TITLE
[DNMY] Add option for security-constrained N-1 optimisation

### PR DESCRIPTION
**Pull request by fneum**
## Changes proposed in this Pull Request

This PR constitutes phase 1 of increasingly accounting for outage events in investment optimisation with PyPSA-Eur. Phase 2 would consist of including functions from @shokriga that determine approximate/robust `s_max_pu` factors for each line.

Changes in https://github.com/PyPSA/PyPSA/pull/178 will allow importing the builder of the N-1 contingency constraints; also for the `nomopyomo` variant.

This PR introduces a new option `SC` or e.g. `SC0.8` for the `{opts}` wildcard (`SC` = security constraints):

> Add N-1 contingency constraints considering outages of any one AC transmission line. Does not consider outages of HVDC links. If a float is appended, a uniform approximate security margin ``s_max_pu`` is applied to all lines (e.g. ``SC0.8`` allows all lines to be used up to 80% or their nominal capacity). Takes precedence over setting ``lines: s_max_pu``.

I also sneaked in a slight change to the `Ep` option:

> Add emission price configured in ``costs: emission_prices: co2`` to ``marginal_cost`` of generators (other emission types listed in ``network.carriers`` possible as well). Alternatively, a carbon-dioxide price can be appended to the option as a float (e.g. ``Ep50.0`` would set a price of 50 EUR/t). Takes precedence over setting ``costs: emission_prices``.

Additionally, some improvements to logging in `prepare_network.py` were made.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- ~[ ] Newly introduced dependencies are added to `environment.yaml` and `environment.docs.yaml`.~
- ~[ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.~
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

### CODE REVIEW

**Comment by fneum** [comment]
https://github.com/PyPSA/pypsa-eur/pull/157/commits/c7ba8af6cfcf8de9e809ffd731c57969fe82b9cd introduces functionality whereby only the outage of one parallel line is considered, rather than all parallel lines at once. This is achieved by splitting each line into an "outage line" with `num_parallel=1` for which we consider outages and the rest with `num_parallel` reduced by one. Outages for original lines with `num_paralllel=1` are also considered. Special handling for lines lifted from 220kV to 280kV is also provided.

Could you review and test this @shokriga?

**Comment by fneum** [comment]
Has performance issues, should work better once xarray-based switch to linopy is done if still needed.

**Comment by euronion** [comment]
Instead of merging we agreed upon today to collect good examples for constraints in the documentation rather than merging. Especially relevant for constraints which require very specific setups.

**Comment by fneum** [comment]
stale

**Pull request closed without merging**
