### PR TITLE
Adjust thickness values according to specification of an industrial product

### PR DESCRIPTION
**Pull request by ekatef**
## Changes proposed in this Pull Request

Regarding equivalent insulation thickness (`l_strength` in the code):
1. The thicknesses must be in fact in inches, as styrofoam is Canadian brand.
2. Our inputs for `l_strength` [determined as 76 mm and 197 mm](<https://github.com/PyPSA/pypsa-eur/blob/6875f4103c91092bea95e682b7c514ec76d55d51/scripts/build_retro_cost.py#L127>) are in fact 3inch and 7.76 inch, respectivelly. The first value is perfectly reasonable according to [Dupont product sheet](<https://www.dupont.com/content/dam/dupont/amer/us/en/performance-building-solutions/public/documents/en/styrofoam-brand-square-edge-st-100-pis-43-d100996-enus.pdf>), while for the second one I'd rather assume 7.5 inch = 3.5 inch + 4 inch = 190.5 mm.
3. Real insulation thickness values differ from `l_strength` according to [the values](<https://github.com/PyPSA/pypsa-eur/blob/6875f4103c91092bea95e682b7c514ec76d55d51/scripts/build_retro_cost.py#L82>) of `l_weight`, 

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Changed dependencies are added to `envs/environment.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [ ] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Comment by fneum** [comment]
Perhaps this was meant for a different branch?

I would suggest handling pull requests that do not target the master branch in a fork of PyPSA-Eur. This will make it a bit easier for me to keep an overview over what needs reviewing. Thanks!

**Comment by ekatef** [comment]
> Perhaps this was meant for a different branch? Reopen if that is not the case.
> 
> I would suggest handling pull requests that do not target the master branch in a fork of PyPSA-Eur. This will make it a bit easier for me to keep an overview over what needs reviewing. Thanks!

Yeah, indeed that was intended for chp_cc. Thanks a lot for checking @fneum!

Agree that it feels weird to work from branches instead of fork. We'll try to figure out a better way.

**Comment by martacki** [comment]
Thanks @fneum for flagging, this is more of a hirstoric ... diverge ... not sure. For future project we will definitely work on a fork, however, some of the features would be also nice to have also in PyPSA-Eur master branch.

**Comment by fneum** [comment]
Not saying anything against contributions to the master! That is most welcome!

**Pull request closed without merging**
