### PR TITLE
prepare for pypsa `0.31.0`

### PR DESCRIPTION
**Pull request by lkstrp**
- Pins `pypsa>=0.31.0`
- Replaces all `n.madd` with `n.add`. This wouldn't break otherwise, but spams deprecation warnings

### CODE REVIEW

**Comment by lkstrp** [comment]
Good to go?

**Comment by fneum** [comment]
The changes made so far look good, but perhaps other similar deprecations should be addressed in one go?:

```
/home/runner/work/pypsa-eur/pypsa-eur/.snakemake/scripts/tmpt6904tfn.base_network.py:794: DeprecatedWarning: import_components_from_dataframe is deprecated as of 0.29 and will be removed in 1.0. Use `n.add` instead. E.g. `n.add(class_name, df.index, **df)`.

WARNING:pypsa.components:Single value sequence for type is treated as a scalar and broadcasted to all components. It is recommended to explicitly pass a scalar instead.

/home/runner/work/pypsa-eur/pypsa-eur/.snakemake/scripts/tmp_f84nzgk.simplify_network.py:128: DeprecatedWarning: mremove is deprecated as of 0.31 and will be removed in 1.0. Use `n.remove` as a drop-in replacement instead.

/home/runner/work/pypsa-eur/pypsa-eur/.snakemake/scripts/tmpdvo4xrrd.cluster_network.py:418: DeprecatedWarning: network is deprecated as of 0.32 and will be removed in 1.0. Use `clustering.n` instead.
```

**Comment by lkstrp** [comment]
Fair

**Comment by fneum** [comment]
Thanks @lkstrp!

**Pull request merged**
