### PR TITLE
match build_powerplants FuelType

### LINKED ISSUE #676: build_powerplants FuelType and Technology bug
## Describe the Bug
Spotted by @energyLS in PyPSA-Earth, fixed by @Tomkourou, and reviewed by me. It was found out that the FuelType and Technology were not correctly assigned in PyPSA-Earth, leading to the following issue: image

PyPSA-Eur trouble code is here:
https://github.com/PyPSA/pypsa-eur/blob/80eadcf24aea9b1805d8ebfa66de0422e10f0c04/scripts/build_powerplants.py#L100-L107

Recommended changes in the [PyPSA-Earth PR applicable to PyPSA-Eur](https://github.com/pypsa-meets-earth/pypsa-earth/pull/754):
- assume that steam turbine is actually CCGT (steam turbine + gas turbine)
- fix assignment bug in `replace_natural_gas_fueltype()`
- replace `.where` by `.mask` for readability improvement

The changes lead to the following correct results:
image

### PR DESCRIPTION
**Pull request by fneum**
Closes #676

### CODE REVIEW

**Comment by FabianHofmann** [comment]
@fneum did you close intentionally? was lgtm

**Comment by fneum** [comment]
Ups. No, but tests did not pass.

**Comment by energyLS** [comment]
@fneum after the implementation of this change we ran into another issue in PyPSA-Earth described here https://github.com/pypsa-meets-earth/pypsa-earth/issues/774 and solved here: https://github.com/pypsa-meets-earth/pypsa-earth/pull/797. Without looking into further detail here, I guess we should integrate the solution in https://github.com/pypsa-meets-earth/pypsa-earth/pull/797 in PyPSA-Eur as well. What do you think? Happy to add it to this PR.

**Comment by fneum** [comment]
@energyLS Thanks for letting me know! Saved me some time going bug hunting.

**Pull request merged**
