### PR TITLE
Add support for the linopy `io_api` option

### PR DESCRIPTION
**Pull request by koen-vg**
Sorry for the barrage of issues and pull requests. I do think this is a nice and simple improvement.

## Changes proposed in this Pull Request

Big fan of the `io_api = "direct"` option that linopy provides for HiGHS and Gurobi; it improves performance and actually solves some problems I've had with .lp files eating up too much disk space on funky cloud setups.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [x] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Comment by koen-vg** [comment]
By the way this isn't worth a new issue but you seem to have accidentally added your personal config to the last commit to master.

**Comment by koen-vg** [comment]
Actually this seems to cause a problem with the snakemake workflow always re-running the solve_network rule; please don't merge until I fix it.

**Comment by koen-vg** [comment]
Nevermind, the re-running thing doesn't seem to be a problem with the present PR but with d145758f! Feel free to merge this if desired.

**Comment by koen-vg** [comment]
> Actually this seems to cause a problem with the snakemake workflow always re-running the solve_network rule; please don't merge until I fix it.

The re-running issue is now fixed in https://github.com/PyPSA/pypsa-eur/pull/893

**Review by fneum — APPROVED** [review]
Nice addition!

Out of curiosity: Performance increases were in terms of memory or time?

**Comment by koen-vg** [comment]
> Out of curiosity: Performance increases were in terms of memory or time?

Definitely in terms of time; using the direct API keeps things in memory meaning that writing the .lp and reading it again is avoided; the time savings surely depend quite a bit on the file system. Of course it shouldn't matter for the time or memory taken by the actual solver: it "doesn't care" if it was fed a problem via python API or .lp file. Total memory use I haven't checked but don't think it changes much overall.

**Pull request merged**
