### PR TITLE
prepare_sector_network.py: add oil bus whenever industry is added

### PR DESCRIPTION
**Pull request by p-glaum**
I got the warning that many links like "naphtha for industry" or "Fischer-Tropsch" had missing bus "EU oil" because it was not declared. Usually, it is always declared because in shipping it was added and also for ICE vehicles. However, when I do an overnight optimization with the time horizon 2050, then we do not have oil demand for shipping and ICE, and the oil bus is not added which led to the warning.

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Changed dependencies are added to `envs/environment.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [ ] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Review by fneum — COMMENTED** [review]
Great, could you move this to the first location where the oil bus is used in `prepare_sector_network`? Trying to stick to the convention that buses should be defined before using them.

**Comment by p-glaum** [comment]
> Great, could you move this to the first location where the oil bus is used in `prepare_sector_network`? Trying to stick to the convention that buses should be defined before using them.

So you mean I add the oil bus in the transport sector, even if ICEs are not considered?

**Comment by p-glaum** [comment]
what one could also do is restructure:
```python
  if snakemake.params.foresight in ["myopic", "perfect"]:
      add_lifetime_wind_solar(n, costs)

      conventional = snakemake.params.conventional_carriers
      for carrier in conventional:
          add_carrier_buses(n, carrier)
```
to 
```python
    if snakemake.params.foresight in ["myopic", "perfect"]:
        add_lifetime_wind_solar(n, costs)

      conventional = snakemake.params.conventional_carriers
      for carrier in conventional:
          add_carrier_buses(n, carrier)
```

**Comment by p-glaum** [comment]
If I do it with a condition whether an option like "biomass_to_liquid" is considered, I would need to add three if clauses in add_biomass

**Comment by fneum** [comment]
Maybe then at top of `add_industry()` we need to rework this anyway, but adding the oil bus in between the shipping is a bit too hidden.

**Comment by p-glaum** [comment]
I moved oil and methnaol to the top of add_industry, because they are always needed. To avoid the warning that bus does not exist in biomass, I added add_carrier_buses to all options.

**Comment by p-glaum** [comment]
> Maybe then at top of `add_industry()` we need to rework this anyway, but adding the oil bus in between the shipping is a bit too hidden.

I agree that we need to rework this in a smart way

**Review by fneum — APPROVED** [review]

**Pull request merged**
