### PR TITLE
Fix broken equity constraints logic

### PR DESCRIPTION
**Pull request by ricnogfer**
…A-Eur-Sec

Closes # (if applicable).

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Changed dependencies are added to `envs/environment.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [ ] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Comment by pz-max** [comment]
@ricnogfer , that for the excellent report. Are your PR changes fixing everything locally now?

**Comment by pz-max** [comment]
@ricnogfer checking the other constraints, e.g. https://github.com/PyPSA/pypsa-eur/blob/b7aa122fdaeeee6c969d1f5429fdca12892caf07/scripts/solve_network.py#L242 

As you mentioned, our current error without using any `to_xarray()` is:
```
TypeError: `group` must be an xarray.DataArray or the name of an xarray variable or dimension. Received Generator
```
Something like: `xr.DataArray(sgrouper).rename(dim_0="group")` could help.

**Actually, could you report the n.objective for both solutions?**
One with your approach, one with the xr.DataArray() approach.
Sometimes things work with the constraint but lead to different results.
The `xr.DataArray()` might also be good for consistency, but your solution seems more compact and might be potentially better if both solutions lead to the same objective.

**Comment by ricnogfer** [comment]
@pz-max, tried to use the alternative that you pointed out (`xr.DataArray(sgrouper).rename(dim_0="group")`) but, unfortunately, without success. It throws the following error:

```
INFO:__main__:No expandable lines found. Skipping iterative solving.
Traceback (most recent call last):
  File "/home/rignogfer/workspace/pypsa-eur_merge/.snakemake/shadow/tmpzgv7r8n4/.snakemake/scripts/tmp66fhp6xt.solve_network.py", line 674, in <module>
    n = solve_network(
  File "/home/rignogfer/workspace/pypsa-eur_merge/.snakemake/shadow/tmpzgv7r8n4/.snakemake/scripts/tmp66fhp6xt.solve_network.py", line 607, in solve_network
    status, condition = n.optimize(
  File "/home/rignogfer/workspace/anaconda3/envs/pypsa-eur/lib/python3.10/site-packages/pypsa/optimization/optimize.py", line 479, in __call__
    return optimize(self._parent, *args, **kwargs)
  File "/home/rignogfer/workspace/anaconda3/envs/pypsa-eur/lib/python3.10/site-packages/pypsa/optimization/optimize.py", line 457, in optimize
    extra_functionality(n, sns)
  File "/home/rignogfer/workspace/pypsa-eur_merge/.snakemake/shadow/tmpzgv7r8n4/.snakemake/scripts/tmp66fhp6xt.solve_network.py", line 581, in extra_functionality
    add_EQ_constraints(n, o)
  File "/home/rignogfer/workspace/pypsa-eur_merge/.snakemake/shadow/tmpzgv7r8n4/.snakemake/scripts/tmp66fhp6xt.solve_network.py", line 301, in add_EQ_constraints
    .groupby(xr.DataArray(ggrouper).rename(dim_0="group"))
  File "/home/rignogfer/workspace/anaconda3/envs/pypsa-eur/lib/python3.10/site-packages/xarray/core/dataarray.py", line 2359, in rename
    dataset = self._to_temp_dataset()._rename(name_dict)
  File "/home/rignogfer/workspace/anaconda3/envs/pypsa-eur/lib/python3.10/site-packages/xarray/core/dataset.py", line 3609, in _rename
    raise ValueError(
ValueError: cannot rename 'dim_0' because it is not a variable or dimension in this dataset
Not cleaning up /home/rignogfer/workspace/pypsa-eur_merge/.snakemake/shadow/tmpzgv7r8n4/.snakemake/scripts/tmp66fhp6xt.solve_network.py
```

**Comment by pz-max** [comment]
@ricnogfer, sure. The code snippet I showed was just an example on how other parts are doing that.
You need to [debug](https://github.com/pypsa-meets-earth/documentation/blob/main/hackathon/4_how_to_debug.ipynb) and analyse:
- where you use the DataArray
- whats the dimension to use etc.

**Comment by koen-vg** [comment]
If there's any findings on grouping and xarrays that I should incorporate into #659, let me know. That version of the equity constraint seems to work fine but it's possible I missed something.

**Pull request merged**
