### PR TITLE
Add pre-commit CI

### PR DESCRIPTION
**Pull request by FabianHofmann**
Closes #302 

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

### CODE REVIEW

**Review by fneum — APPROVED** [review]

**Comment by fneum** [comment]
Oh, god, look at all those typos!

**Comment by FabianHofmann** [comment]
> Oh, god, look at all those typos!

:D

**Comment by fneum** [comment]
Lifting ipopt version constraint in CI helps CI to complete, see #417

**Comment by fneum** [comment]
You might also need to check (if the indentation of `environment.yaml` changed) how glpk and ipopt are added in the Github Action.

**Pull request merged**
