### PR TITLE
plot_network.py: fix for cartopy issue in pypsa/plot.py

### PR DESCRIPTION
**Pull request by Heronimonimo**
Quick fix for #50 as discussed in while waiting for definitive solution in PyPSA/PyPSA#75.

### CODE REVIEW

**Comment by Heronimonimo** [comment]
One thing to make shure is that changes also work for those running a pypsa version from conda-forge.

**Comment by fneum** [comment]
This should actually work for the current conda-forge version.

I made a few minor changes to your PR.
* One of the plots should not plot the country outlines.
* plt.subplots() still requires the original figsize argument.

**Comment by Heronimonimo** [comment]
> This should actually work for the current conda-forge version of PyPSA if I am not mistaken.
> 
> I made a few minor changes to your PR.
> 
> * One of the plots should not plot the country outlines.
> * plt.subplots() still requires the original figsize argument.

I'm using the conda-forge version and unfortunately it doesn't work for me, still getting:
`UnboundLocalError: local variable 'use_cartopy' referenced before assignment`

In my case `geomap=True` is needed in the `n.plot` to fix it.

**Comment by FabianHofmann** [comment]
>I'm using the conda-forge version and unfortunately after the changes you made it doesn't work for me, getting:
>UnboundLocalError: local variable 'use_cartopy' referenced before assignment
>
>In my case geomap=True is needed in the n.plot to fix it.

Yes, I think so too. The geomap=True is necessary to not run into the (purely) pypsa bug. As I see right now, the only disadvantage is slightly thicker borders when plotting two times with geomap=True

**Comment by fneum** [comment]
Ah, ok. Sorry for the misunderstanding. We should just keep in mind then to turn `geomap=False` in the second `n.plot()` once we have a new PyPSA release.

**Comment by coroa** [comment]
Will merge after the PR solves #50 completely. Ie, it handles plotting of technologies with carriers like `OCGT-ext`. For reference, these technology "sub"-types were included too allow fixed and extendable powerplants at the same time. I think it would be best to fall back to using the `OCGT` only `tech_colors` in such a case. I think they are only possible for conventional generators.

**Comment by FabianHofmann** [comment]
close as outdated

**Pull request closed without merging**
