### PR TITLE
feat: prioritize mamba over conda, allow passing environment target name to installation

### PR DESCRIPTION
**Pull request by FabianHofmann**
Closes # (if applicable).

## Checklist

- [x] I tested my contribution locally and it works as intended.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in `config/config.default.yaml`.
- [x] Changes in configuration options are documented in `doc/configtables/*.csv`.
- [x] Sources of newly added data are documented in `doc/data_sources.rst`.
- [x] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Comment by lkstrp** [comment]
Just added an option to keep conda prioritised. I couldn't find a nice way to activate the environment. It is possible (see [here](https://stackoverflow.com/questions/53382383/makefile-cant-use-conda-activate)), but some PATHS would still be missing after activation, and we don't want to fix a shell/ os/ conda vs. mamba

**Comment by FabianHofmann** [comment]
sure thing, how would I prefer conda? passing it as an argument?

**Comment by lkstrp** [comment]
`export PYPSA_PREFER_CONDA=true` in your `.zshrc`/ `.bashrc`

**Comment by FabianHofmann** [comment]
perfect!

**Pull request merged**
