### PR TITLE
Change PyPSA-Eur licence from copyleft GPLv3 to more liberal MIT

### PR DESCRIPTION
**Pull request by fneum**
Similar to PyPSA earlier this summer, with this pull request the licence for PyPSA-Eur would be changed from the copyleft GNU General Public License Version 3 (GPLv3) to the more liberal MIT License.

This change is suggested because the benefits of a more liberal license seem to outweigh the benefits of a copyleft approach.

For a discussion of the benefits of either license see https://github.com/PyPSA/PyPSA/pull/274

This change requires the consent of all people who have substantially contributed code to PyPSA-Eur. If you consent, please reply with a :heavy_check_mark: below. If you do not consent, please reply with a :x: below. Please respond by 21st September 2021. Please feel free to also discuss below. Thanks for your help!

### Consent Essential (>= 20 lines of code)

@coroa :heavy_check_mark: 
@fneum :heavy_check_mark: 
@FabianHofmann :heavy_check_mark: 
@martacki :heavy_check_mark: 
@Heronimonimo :heavy_check_mark: 
@euronion :heavy_check_mark: 
@nworbmot :heavy_check_mark: 
@JanFrederickUnnewehr :heavy_check_mark: 
@pz-max :heavy_check_mark: 

### Consent Appreciated (< 20 lines of code)

@chiaroo :heavy_check_mark: 
@koen-vg :heavy_check_mark: 
@lukasnacken :heavy_check_mark: 
@arnaud-leroy 
@huckebrink :heavy_check_mark:

### CODE REVIEW

**Comment by martacki** [comment]
heavy_check_mark

**Comment by fneum** [comment]
:heavy_check_mark:

**Comment by martacki** [comment]
:heavy_check_mark:

**Comment by huckebrink** [comment]
✔️

**Comment by nworbmot** [comment]
heavy_check_mark

**Comment by pz-max** [comment]
:heavy_check_mark:

**Comment by FabianHofmann** [comment]
:heavy_check_mark:

**Comment by Heronimonimo** [comment]
✔️

**Comment by JanFrederickUnnewehr** [comment]
✔️

**Comment by koen-vg** [comment]
✔

**Comment by lukasnacken** [comment]
✔️ 👍

**Comment by chiaroo** [comment]
✔

**Comment by coroa** [comment]
✔️

**Comment by euronion** [comment]
✔️

**Comment by fneum** [comment]
I find that all required consents for a licence change from GPLv3 to MIT have been received.

**Comment by fneum** [comment]
Ok, so for some unidentified reason PROJ8 does not yet work. I would just wait and see.

**Pull request merged**
