### PR TITLE
Dynamic line rating

### PR DESCRIPTION
**Pull request by fneum**
@p-glaum @FabianHofmann cherry-picked from your `line-rating` branch.

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [x] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
This look quite good! @p-glaum we did not use the max_voltage setting in the end as it was far from necessary, right? I think we can remove that option.
It is a lot of commit, for a quite medium size change. Maybe we can squash it...

**Comment by fneum** [comment]
> It is a lot of commit, for a quite medium size change. Maybe we can squash it...

Could, but this would muddle with the code contribution stats. We've had PRs with more commits ;)

**Review by FabianHofmann — APPROVED** [review]
great!

**Comment by FabianHofmann** [comment]
@fneum I saw that the CI wasn't using the `be` cutout for the line-rating. I also moved the cutout specification to the `lines: dynamic_line_rating:` section.

**Pull request merged**
