### PR TITLE
no defaults channel in environment.yaml

### LINKED ISSUE #142: Create conda environment, results in “Found conflicts!”
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/environment.yaml). Update via `conda env update -f environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

The creation of the environment currently leads to compatibility errors between packages.
Recently you added the "defaults" channel to the `environment.yaml` file. Getting some packages from different channels can lead to the error listed below. By commenting out the line 3 `- defaults` in the `.yaml` file the environment is created successfully.

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```
(base) freddy@intgrid-pc-08:~/Dokumente/pypsa-eur_50/pypsa-eur$ conda env create -f environment.yaml
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

### PR DESCRIPTION
**Pull request by fneum**
Fixes #142 
Let's see...

### CODE REVIEW

**Comment by coroa** [comment]
Channel pinning should be superseeded by setting channel priority to strict as explained here: https://conda-forge.org/docs/user/tipsandtricks.html

Apart from that, it seems descartes is pulled in too late by pip and should probably be uplifted to a conda dependency instead.

**Comment by fneum** [comment]
Pity there's not yet a way to request strict channel priority in the `environment.yaml`: https://github.com/conda/conda/issues/8675

```bash
conda config --set channel_priority strict
```

**Comment by coroa** [comment]
Failure on mac:
```
ImportError: dlopen(/Users/travis/miniconda/envs/pypsa-eur/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libwebp.7.dylib

  Referenced from: /Users/travis/miniconda/envs/pypsa-eur/lib/libtiff.5.dylib

  Reason: Incompatible library version: libtiff.5.dylib requires version 9.0.0 or later, but libwebp.7.dylib provides version 8.0.0
```

Both are from conda-forge:
```
libtiff                   4.1.0                h2ae36a8_5    conda-forge
libwebp                   1.0.2                hd3bf737_5    conda-forge
libwebp-base              1.1.0                         2    conda-forge
```

Should be missing deps in the `libtiff` or `libwebp` conda recipes.

Found https://github.com/conda-forge/libtiff-feedstock/issues/56 and https://github.com/conda-forge/libwebp-feedstock/issues/26 so seems to be a known active problem. We maybe could constrain libwebp down a bit, but this will be a pain to find out, if we can only test on the travis mac runners.

**Comment by fneum** [comment]
@FabianHofmann everything seems to work with/without `defaults` channel. I'm on the fence about keeping or removing it. What's your view?

**Pull request merged**
