### PR TITLE
Clustering: build renewable profiles and add all assets after clustering

### LINKED ISSUE #1189: Build renewable profiles and add all assets after the clustering
* Currently renewable profiles and load are added to the high-resolution base network, then it is clustered. This makes the clustering highly dependent on the substation layout of the base network.
* This was an artefact of @coroa's [original paper exploring clustering](https://arxiv.org/abs/1705.07617) of the base network
* If we separate the clustering from the network, we are free to cluster on e.g. custom shapes, or cluster based on weather cells instead
* Generating renewable profiles after clustering requires fewer computations (num clusters instead of 5000 base substations)
*  It would be easier to switch to allowing multiple VRE LCOE-classes inside each region rather than tying them to sub-regions.
*  We would avoid the weirdnesses that some assets are added before, some added after the clustering - we could uniformise around PyPSA-Eur-Sec-style "assets added after clustering". This would simplify the workflow considerably.
*  Downside: if you want to cluster based on VRE time series, you have to do extra work (but at least you're not tied to substation layout - you could e.g. cluster time series from the original weather cells)

### LINKED ISSUE #1216: Work out why p_max_pu are different in myopic code for existing assets
There is some weirdness in the myopic foresight code either in `add_existing_baseyear` or `add_brownfield` whereby wind turbines built in the first investment year and before have different `p_max_pu` than later wind turbines, even though the wind turbine model stays the same. Here is an example for investment year 2025, where the first investment year is 2020.

Screenshot from 2024-08-14 13-57-41

### PR DESCRIPTION
**Pull request by fneum**
Closes #1189.
Closes #1216.

## Changes proposed in this Pull Request

- Moved rules `simplify_network` and `cluster_network` before `add_electricity` and `build_renewable_profiles`
- Split rule `build_renewable_profiles` into two separate rules, `determine_availability_matrix` for land eligibility analysis and `build_renewable_profiles`, which now only computes the profiles and total potentials from the pre-computed availability matrix.
- Removed variables `weight` and `potential` from output of `build_renewable_profiles` as it is no longer needed
- HAC-clustering is now based on wind speeds and irradiation time series rather than capacity factors
- Added new rule `build_hac_features` that aggregates cutout weather data to base regions
- Removed `{simpl}` wildcard and all associated code of the `m` suffix of the `{cluster}` wildcard. This means that the option to pre-cluster the network in `simplify_network` was removed. It will be superseded by clustering renewable profiles and potentials within clustered regions by resource classes.
- The rule `build_line_rating` now directly attaches the DLR profiles to the `pypsa.Network` which is then returned as output.
- The rule `add_extra_components` was integrated into `add_electricity`
- Added new rule `build_electricity_demand_base` to determine the load distribution of the substations in the base network (which was previously done in `add_electricity`). This time series is used as weights for kmeans-clustering in `cluster_network` and is later added to the network in `add_electricity` in aggregated form.
- The weights of the kmeans clustering algorithm are now exclusively based on the load distribution. Previously, they also included the distribution of thermal capacity.
- Since the networks no longer start with the whole electricity system added pre-clustering, the files have been renamed from `elec...nc` to `base...nc`.
- The scripts `simplify_network.py` and `cluster_network.py` were simplified to become less nested and profited from the removed need to deal with cost data.
- New configuration options to calculate connection costs of offshore wind plants.
- Offshore connection costs are now calculated based on the underwater distance to the shoreline plus a configurable `landfall_length` which defaults to 10 km. Previously the distance to the region's centroid was used, which is not practical when the regions are already aggregated.

## Updated Workflow Graph

intro-workflow

## Testing

A first observation is that `build_renewable_profiles` on clustered regions is much faster!

Without a doubt, this PR is not going to be backward compatible, which is why it should be pulled after a v0.12.0 release.

## Next steps

- Cluster renewable profiles and potentials within clustered regions by resource classes, emulating the previous `m` option in `{clusters}` wildcard, but better.
- Add option to cluster by administrative shapes #263.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [x] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Comment by cpschau** [comment]
Capacity factors pre-solve seem to be spot on!

cf_comparison_64
cf_comparison_128
cf_comparison_256
cf_comparison_512

**Comment by cpschau** [comment]
shape_comparison_cluster_64
shape_comparison_cluster_128
shape_comparison_cluster_256
shape_comparison_cluster_512

**Comment by FabianHofmann** [comment]
@fneum this is awesome. One minor comment about the infixes (will have a deeper look when there is time). I was wondering why we keep the  `_s_` infix. It seems that this is because the dlr is still done before clustering. However, I doubt that this actually makes much sense. First calculating dlr and clustering, is probably as bad as first clustering and then calculating dlr. The reason being that one does not know which of the clustered transmission lines are parallel and which are in series.

**Comment by lisazeyen** [comment]
Change in `capital_cost` for offwind depending on later or earlier clustering for 37 nodes
offwind-ac-later-clustering
offwind-dc-capitalcost

**Comment by lisazeyen** [comment]
Changes in `p_nom_max`. In general, seems to be quite similar
higher solar potential in Norway
solar-p_nom_max
onwind
onwind-p_nom_max
offwind-ac
offwind-ac-p_nom_max

Warning for the following nodes that installed capacity is larger than technical potential
`['BE1 0 offwind-ac-2025', 'DE1 0 offwind-ac-2025',
       'GB5 0 offwind-ac-2025', 'NL1 0 offwind-ac-2025', 'ES4 0 onwind-2025',
       'ES4 0 solar-2025']`

**Comment by lisazeyen** [comment]
Change in `offwind-ac`profiles for 37 nodes
offwind-ac-distance
offwind-ac-underwater

**Comment by lisazeyen** [comment]
> Change in `offwind-ac`profiles for 37 nodes offwind-ac-distance offwind-ac-underwater

this is not important anymore since underwater fraction is removed in this PR

**Comment by lisazeyen** [comment]
Looks good to me now! Just the `offwind-float` capital cost seem to increase somewhat. Amazing, that the investment costs are so similar now even though the calculation is quite different...

**Comment by lisazeyen** [comment]
When checking the `p_max_pu` for onshore and offshore wind I see some larger deviations, for example for Belgium
diff-pmaxpu-offwind-dc-BE1 0
example-week-offwind-dc-BE1 0
diff-pmaxpu-onwind-BE1 0
example-week-onwind-BE1 0
diff-pmaxpu-offwind-float-BE1 0
example-week-offwind-float-BE1 0
diff-pmaxpu-offwind-ac-BE1 0
example-week-offwind-ac-BE1 0

**Comment by lisazeyen** [comment]
run of river in LU is missing in feature branch, Italy as slightly larger capacities. Overall summed capacity of ror stays constant.
pnom_ror

**Comment by fneum** [comment]
Ready to be merged from my side @lisazeyen, @cpschau, @FabianHofmann. Now is a good time as there are not too many other open PRs.

**Comment by lisazeyen** [comment]
> Ready to be merged from my side @lisazeyen, @cpschau, @FabianHofmann. Most tests pass, I extensively tested and compared the outputs. Now is a good time as there are not too many other open PRs and there was a recent release. It's much faster :)

Great, looks good to me!

**Comment by cpschau** [comment]
> Ready to be merged from my side @lisazeyen, @cpschau, @FabianHofmann. Most tests pass, I extensively tested and compared the outputs. Now is a good time as there are not too many other open PRs and there was a recent release. It's much faster :)

Great! Looking very much forward to the fast RES profiles build!

**Comment by FabianHofmann** [comment]
let's do it! :rocket:

**Pull request merged**
