### PR TITLE
harmonize output of solving rules

### PR DESCRIPTION
**Pull request by FabianHofmann**
only copy active configuration to results folder
use copy config for all solve rules
remove copying of environment

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv`.
- [x] A release note `doc/release_notes.rst` is added.

### CODE REVIEW

**Review by fneum — APPROVED** [review]
LGTM. We could think of adding a commit-hash to `n.meta`, like `abcd1234-dirty` to follow version of preparation and solving scripts.

**Comment by FabianHofmann** [comment]
> LGTM. We could think of adding a commit-hash to `n.meta`, like `abcd1234-dirty` to follow version of preparation and solving scripts.

Indeed, and since we are storing the config in the network meta anyway, should we just get rid of the copy config for good?

**Comment by fneum** [comment]
Hmm, you're right that there's some duplication but maybe a YAML is easier to inspect ad-hoc.

**Comment by lisazeyen** [comment]
> 

I would favor keeping the .yaml file. It is also useful if you want to use it for a summary script of all scenarios since you do not have to read in a pypsa network to check the n.meta

**Pull request merged**
