### PR TITLE
#624 Rename build_load_data to build_electricity_demand

### LINKED ISSUE #624: Rename `build_load_data` to `build_electricity_demand`

### PR DESCRIPTION
**Pull request by Ahmad-Wahid**
fixes #624 
## Changes proposed in this Pull Request
- Renamed build_load_data to build_electricity_demand

### CODE REVIEW

**Review by fneum — CHANGES_REQUESTED** [review]
@Ahmad-Wahid, cheers for this contribution!

There are a few more references to `build_load_data` in the repository (e.g. in the documentation). Could you change that to `build_electricity_demand`, too?

**Comment by Ahmad-Wahid** [comment]
sure, I will update that.

**Comment by Ahmad-Wahid** [comment]
@fneum hey I'm not sure about this pre-commit.ci thing. It's failed. would you tell that how can I fix it? I'm still new to git

**Review by fneum — CHANGES_REQUESTED** [review]
You don't need to worry about the pre-commit. It's likely because of the version update of docformatter.

There are 3 more references to build_load_data that should be adapted:

- doc/preparation.rst
- doc/release_notes.rst
- scripts/build_electricity_demand.py -> mock_snakemake

Could you also add a release note in doc/release_notes.rst mentioning the renaming?

Then, we're good to merge.

**Review by fneum — APPROVED** [review]

**Pull request merged**
