### PR TITLE
Fix distribute clustering with cbc/glpk/ipopt

### PR DESCRIPTION
**Pull request by pz-max**
In PyPSA-Africa an error appeared while clustering two countries:
`OverflowError: cannot convert float infinity to integer`
(CI in PyPSA-Eur only considers 1 country). This PR fixes the issue.

Assume you have 10 nodes that need to be distributed between 2 countries.
What can happen with some of the open-source solvers is that one country
gets assigned to 9.01 (float) nodes, and the other one to 0.99.

Now using .astype(int) would lead to a node distribution of 0 and 9, as
the `astype(int)` function round down by default (0.99 -> 0). This assigned
zero value breaks the code in case open source solvers are used.

Gurobi somehow does deal with it. Therefore the error was not detected previously.

Closes #

## Changes proposed in this Pull Request
add `.round()`

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.

### CODE REVIEW

**Review by fneum — APPROVED** [review]

**Comment by fneum** [comment]
@martacki could you check whether this may have unintended consequences?

**Comment by martacki** [comment]
Can't see any unintended consequences @fneum.
But I wonder, how can it happen that you get 9.01/0.99 ?nBecause we're minimizing in an integer domain. So getting something like 9.01 suggests an error elsewhere to me.

**Comment by pz-max** [comment]
Probably an error introduced somewhere in pyomo (po)?
Gurobi did not cause any trouble.

**Comment by pz-max** [comment]
Awesome. Thanks @martacki and @fneum ! :100:

**Pull request merged**
