### PR TITLE
Propagate the solver log file name to the solver

### PR DESCRIPTION
**Pull request by koen-vg**
Previously, the PyPSA network solving functions were not told about
the solver logfile specified in the Snakemake file. This small addition fixes that.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

### CODE REVIEW

**Comment by fneum** [comment]
Very interesting. Never noticed. I would do it slightly differently:

1. Change `solver_log` to `solver_logfile` to align with corresponding `n.lopf()` argument.

https://github.com/PyPSA/pypsa-eur/blob/11af828c394faca3de4c3050b531e95605b678d4/scripts/solve_network.py#L285-L286

2. Remove `solver_log` from function.

https://github.com/PyPSA/pypsa-eur/blob/11af828c394faca3de4c3050b531e95605b678d4/scripts/solve_network.py#L244

Then `solver_logfile` should automatically be passed through via the `**kwargs`.

**Comment by koen-vg** [comment]
Yes, I like that idea: it's a little more elegant. I'll push the change to the branch.

**Comment by fneum** [comment]
Great, thanks!

**Comment by koen-vg** [comment]
Luckily I also noticed a corresponding situation in `solve_operations_network`. Now I am sure that I checked all two references to the `solve_network` function.

**Review by fneum — APPROVED** [review]

**Comment by fneum** [comment]
Will merge as soon as tests have passed. Thanks!

**Pull request merged**
